export const GET_PHONES = 'GET_PHONES';
export const SELECTED_PHONE = 'SELECTED_PHONE';
export const PHONE_CLICKED = 'PHONE_CLICKED';
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS';
export const GET_PHONES_LOADING = 'GET_PHONES_LOADING';
export const GET_PHONES_FAILED = 'GET_PHONES_FAILED';
